# Generated by Django 4.2.6 on 2023-11-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0003_alter_wrapper_options_icecream_output_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecream',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
