# Generated by Django 4.2.6 on 2023-11-01 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0004_icecream_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icecream',
            options={'ordering': ('output_order', 'title'), 'verbose_name': 'морожение', 'verbose_name_plural': 'Мороженое'},
        ),
    ]
